static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 28080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: http_webapp
          access_log:
          - name: http_access_loggers
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              log_format:
                json_format:
                  protocol: "%PROTOCOL%"
                  duration: "%DURATION%"
                  upstream_host: "%UPSTREAM_HOST%"
                  bytes_received: "%BYTES_RECEIVED%"
                  x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
                  bytes_sent: "%BYTES_SENT%"
                  downstream_local_address: "%DOWNSTREAM_LOCAL_ADDRESS_WITHOUT_PORT%"
                  downstream_local_port: "%DOWNSTREAM_LOCAL_PORT%"
                  user_agent: "%REQ(USER-AGENT)%"
                  response_code: "%RESPONSE_CODE%"
                  response_flags: "%RESPONSE_FLAGS%"
                  start_time: "%START_TIME%"
                  http_method: "%REQ(:METHOD)%"
                  request_id: "%REQ(X-REQUEST-ID)%"
                  requested_server_name: "%REQUESTED_SERVER_NAME%"
                  path: "%REQ(:PATH)%"
                  response_code_details: "%RESPONSE_CODE_DETAILS%"
                  upstream_cluster: "%UPSTREAM_CLUSTER%"
                  upstream_local_address: "%UPSTREAM_LOCAL_ADDRESS_WITHOUT_PORT%"
                  upstream_local_port: "%UPSTREAM_LOCAL_PORT%"
                  upstream_service_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
                  upstream_transport_failure_reason: "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
          route_config:
            name: http_route
            virtual_hosts:
            - name: webapp
              domains:
              # TODO: routes based on hostnames
              - "*"
              routes:
              # TODO: routes based on URIs
              - match:
                  prefix: "/"
                route:
                  cluster: service-webapp
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  - name: tcp_proxy_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 23333
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: webapp_tcp_proxy
          cluster: service-webapp
          access_log:
            - name: tcp_access_loggers
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                log_format:
                  json_format:
                    duration: "%DURATION%"
                    requested_server_name: "%REQUESTED_SERVER_NAME%"
                    upstream_host: "%UPSTREAM_HOST%"
                    bytes_received: "%BYTES_RECEIVED%"
                    bytes_sent: "%BYTES_SENT%"
                    downstream_local_address: "%DOWNSTREAM_LOCAL_ADDRESS_WITHOUT_PORT%"
                    downstream_local_port: "%DOWNSTREAM_LOCAL_PORT%"
                    start_time: "%START_TIME%"
                    response_code_details: "%RESPONSE_CODE_DETAILS%"
                    virtual_cluster_name: "%VIRTUAL_CLUSTER_NAME%"
                    upstream_cluster: "%UPSTREAM_CLUSTER%"
                    upstream_local_address: "%UPSTREAM_LOCAL_ADDRESS_WITHOUT_PORT%"
                    upstream_local_port: "%UPSTREAM_LOCAL_PORT%"
                    upstream_transport_failure_reason: "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
  clusters:
  - name: service-webapp
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: webapp
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: webapp1
                port_value: 8080
        - endpoint:
            address:
              socket_address:
                address: webapp2
                port_value: 8080

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001

# metrics URI: /stats/prometheus

