version: '3'
services:
  webapp1:
    build:
      context: ./webapp
    networks:
      - proxy-demo
    ports:
      - 8091:8080
    volumes:
      - ./env/webapp1:/app/logs
      - ./webapp/:/usr/src/app/
    command:
      # Start Uvicorn Server
      - "uvicorn"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "--workers"
      - "1"
      - "--log-config"
      - "logger.conf.yaml"
      - "app1:app"
  webapp2:
    build:
      context: ./webapp
    networks:
      - proxy-demo
    ports:
      - 8092:8080
    volumes:
      - ./env/webapp2:/app/logs
      - ./webapp/:/usr/src/app/
    command:
      # Start Uvicorn Server
      - "uvicorn"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "--workers"
      - "1"
      - "--log-config"
      - "logger.conf.yaml"
      - "app2:app"
  envoy:
    image: docker.io/envoyproxy/envoy:v1.31.5
    volumes: ./envoy/config.yaml:/envoy/config.yaml
    privileged: true
    networks:
      - proxy-demo
    ports:
      # admin UI
      - 7001:8001
      # HTTP proxy
      - 28080:28080
      # TCP proxy
      - 23333:23333
    command:
      - "-c"
      - "/envoy/config.yaml"
  traefik:
    image: docker.io/library/traefik:v3.3.4
    volumes:
    - ./traefik/static.yaml:/traefik/static.yaml
    - ./traefik/webapp.yaml:/traefik/dynamic/webapp.yaml
    networks:
      - proxy-demo
    ports:
      # admin UI
      - 7002:8080
      # metrics
      - 8081:8081
      # HTTP proxy
      - 21080:21080
      # TCP proxy
      - 21313:21313
    command:
      - "--configfile"
      - "/traefik/static.yaml"
  nginx:
    image: docker.io/bitnami/nginx:1.27.3
    volumes:
      - ./nginx/full.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
      - ./nginx/index.json:/var/nginx/static/json/index.json:ro
    networks:
      - proxy-demo
    ports:
      - 16553:16553 # http
      - 26553:26553 # tcp

networks:
  proxy-demo:
