api:
  insecure: true

# log:
#   level: DEBUG

accesslog:
  addInternals: true
  format: json

metrics:
  prometheus:
    entryPoint: metrics
    buckets:
      - 0.0005
      - 0.0006
      - 0.0007
      - 0.0008
      - 0.0009
      - 0.01
      - 0.05
      - 0.1
      - 1
      - 10

entryPoints:
  http:
    address: ":21080"
  tcp:
    address: ":21313"
  metrics:
    address: ":8081"

providers:
  file:
    directory: "/traefik/dynamic/"
