api:
  insecure: true

# log:
#   level: DEBUG

accesslog:
  addInternals: true

metrics:
  prometheus:
    entryPoint: metrics
    buckets:
      - 0.001
      - 0.01
      - 0.025
      - 0.05
      - 0.075
      - 0.1
      - 0.25
      - 0.5
      - 0.75
      - 1
      - 5
      - 10
      - 20

entryPoints:
  svc:
    address: ":21080"
  metrics:
    address: ":8081"

providers:
  file:
    directory: "/traefik/dynamic/"
